### ISSUE TITLE
pip install not up to date

### ISSUE THREAD

**Issue by RudieKantFail** [matthias-k/pysaliency#12]
Hi!

I have tried to pip install pysaliency but the code I obtained does not seem up to date with the one on this repo (for example it still includes the unsupported imports from scipy.misc).

I have tried to download the code and install it directly but I have run into a number of problems.
Here are the steps which I believe yielded the best results :
- download and unzip the project
- move pysaliency-master to /home/me/.local/lib/python3.6/site-packages/
- cd to pysaliency-master and run python3 setup.py build_ext --inplace

When I try to run a script containing the quickstart  I get the following error :
Traceback (most recent call last):
  File "AIM_main.py", line 6, in <module>
    mit_stimuli, mit_fixations = pysaliency.external_datasets.get_mit1003(location=dataset_location)
AttributeError: module 'pysaliency' has no attribute 'external_datasets'
where AIM_main.py is the name of my script.

I am using python 3.6 on Ubuntu 18.4 and am using Octave (although I doubt Octave has anything to do with this particular error).

Hope I have been clear,
Many thanks in advance

**Comment by matthias-k** [comment]
Hi, thanks for  your report.

I did actually not update pypi for quite some time. I just uploaded the newest version. However, there will always be some chance that the version in github is more up to date than pypi. For installing from github, I always made good experience with `pip install git+https://github.com/matthias-k/pysaliency.git`. Then all imports should work.

**Comment by wassimbensalem** [comment]
Hi ,



> Hi, thanks for your report.
> 
> I did actually not update pypi for quite some time. I just uploaded the newest version. However, there will always be some chance that the version in github is more up to date than pypi. For installing from github, I always made good experience with `pip install git+https://github.com/matthias-k/pysaliency.git`. Then all imports should work.

Hi ,

I tried your command pip install git+https://github.com/matthias-k/pysaliency.git
but i am still getting the same error . 
Is there any other Solution ? 

Thanks a lot !

**Comment by matthias-k** [comment]
Hi @wassimbensalem that is very strange. Maybe there is still some leftover corrupt pysaliency installation in your system from your earlier attempts? In some situation `pip install` doesn't install the package because it's already there. You could try `pip install --upgrade git+https://github.com/matthias-k/pysaliency.git`.

Also, check where you system imports pysaliency from and whether there is a `pysaliency/external_datasets.py`.

**Comment by wassimbensalem** [comment]
If i use the pip .. i will get the following error
ERROR: Package 'imageio' requires a different Python: 2.7.17 not in '>=3.5'
and if i use the pip3.. i get this : 
... 
building 'pysaliency.roc' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/pysaliency
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c pysaliency/roc.c -o build/temp.macosx-10.9-x86_64-3.7/pysaliency/roc.o -fopenmp -O3
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w2/ybqsjm1j2mx6_fn4ssghpxr40000gn/T/pip-req-build-ovmv1gyb/setup.py'"'"'; __file__='"'"'/private/var/folders/w2/ybqsjm1j2mx6_fn4ssghpxr40000gn/T/pip-req-build-ovmv1gyb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w2/ybqsjm1j2mx6_fn4ssghpxr40000gn/T/pip-record-qgz1a35x/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by matthias-k** [comment]
@wassimbensalem pysaliency doesn't support python2 anymore, which reached its end of life.

The error about an unsupported option `-fopenmp` suggests that you don't have openmp installed on your system. However, I realized that I don't use openmp anymore, so I just removed this dependency from master. Please try again to install from master.
