### ISSUE TITLE
About salicon-2017 evaluation

### ISSUE THREAD

**Issue by guyuchao** [matthias-k/pysaliency#14]
The gaze locations of salicon-2017 challenge have a few points beyond the image boundary. For example, the image size is (480,640) but the gaze location is (xxx,641). The question is how to deal with these points in the evaluation. In this code, it raises out-of-bound error.

**Comment by lumosity4tpj** [comment]
> The gaze locations of salicon-2017 challenge have a few points beyond the image boundary. For example, the image size is (480,640) but the gaze location is (xxx,641). The question is how to deal with these points in the evaluation. In this code, it raises out-of-bound error.

Hi, Did you solve it? How did you solve it?

**Comment by matthias-k** [comment]
I recommend to just remove all fixations that are outside of the stimulus size. In some other datasets, the filtering is already done on import but I did not expect this to be a problem in SALICON. It should be easy, though, to apply a filter to the fixations instance for removing all outside fixations.
