### ISSUE TITLE
Unable to download MIT1003 in Colab

### ISSUE THREAD

**Issue by shilpamathew14** [matthias-k/pysaliency#20]
I wanted to download MIT1003 dataset in colab environment. As suggested in Readme, I tried intslling octave and other packages. Still it runs to an error 

I installed octave and related packages in Colab via ! apt install octave
                                                                                   ! apt install octave liboctave-dev
                                                                                   ! apt install octave-statistics
                                                                                   ! apt install octave-image

Running this 

dataset_location = 'datasets'
model_location = 'models'
mit_stimuli, mit_fixations = pysaliency.external_datasets.get_mit1003(location=dataset_location)

It went to an error as shown:

Downloading file: 235MB [00:07, 33.3MB/s]                           
Checking md5 sum...
Downloading file: 47.1MB [00:02, 23.1MB/s]                            
Checking md5 sum...
Downloading file: 32.8kB [00:00, 430kB/s]                    
Checking md5 sum...
Creating stimuli
Creating fixations
Running original code to extract fixations. This can take some minutes.
Warning: In the IPython Notebook, the output is shown on the console instead of the notebook.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-9-7ec9a83aa292> in <module>()
      3 
      4 
----> 5 mit_stimuli, mit_fixations = pysaliency.external_datasets.get_mit1003(location=dataset_location)
      

3 frames
/usr/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
    361         if cmd is None:
    362             cmd = popenargs[0]
--> 363         raise CalledProcessError(retcode, cmd)
    364     return 0
    365 

CalledProcessError: Command '['/usr/bin/octave', '--traditional', '--eval', "try;extract_all_fixations;;catch exc;struct_levels_to_print(10);print_struct_array_contents(true);disp(lasterror);for i=1:size(lasterror.stack);disp(lasterror.stack(i));end;disp('__ERROR__');exit(1);end;quit"]' returned non-zero exit status 1.

Any solution to this issue??? Please

**Comment by matthias-k** [comment]
Unfortunately the MIT1003 dataset extraction doesn't work with octave since octave is too incompatible with matlab. If you don't have matlab, I could send you the preextracted dataset privately.

**Comment by Simon-Zhen** [comment]
> Unfortunately the MIT1003 dataset extraction doesn't work with octave since octave is too incompatible with matlab. If you don't have matlab, I could send you the preextracted dataset privately.

Hello [matthias](https://github.com/matthias-k), I also encountered the same problem. Can you send me the data too?
My email is：simonzhen@tencent.com

Thx a lot
Best
Simon
