### ISSUE TITLE
Context Aware Saliency

### ISSUE THREAD

**Issue by Densus100** [matthias-k/pysaliency#23]
recently there are cyber attacks on technion university, so i can't access the ContextAwareSaliency from them. are there any alternative links or model for ContextAwareSaliency ? thank you

**Comment by matthias-k** [comment]
I couldn't find a proper public download link and have contacted the authors. In the meantime, I found an working link in the webarchived versions of the page (https://web.archive.org/web/20230106184636/https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Software/Saliency/Saliency.html)
