### ISSUE TITLE
google_drive download code is invalid

### ISSUE THREAD

**Issue by yfding98** [matthias-k/pysaliency#25]
pysaliency.external_datasets._get_SALICON_stimuli  
          #1293 
          download_file_from_google_drive('1g8j-hTT-51IG1UFwP0xTGhLdgIUCW5e5', stimuli_file)
          check_file_hash(stimuli_file, 'eb2a1bb706633d1b31fc2e01422c5757')

**Comment by Simon1998China** [comment]
my pysaliency version is : 0.2.21

**Comment by matthias-k** [comment]
Could you check with the dev-branch? There it works for me, if `gdown` is sufficiently recent.

**Comment by ahnchive** [comment]
(solved) I tested it with pysaliency 0.2.22 and Matlab 2023a. I'm not sure what the issue was, but it suddenly started working after several attempts to fix the coordination between Python and Matlab : https://github.com/matthias-k/pysaliency/issues/15

**Comment by matthias-k** [comment]
A possible explanation might be that the SALICON gdrive account ran into its quota. We have seen that with quite some google hosted datasets here, where too many people downloaded them in the same month. Let me know if it happens again and please add a full stack trace and error message.
