### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by leongatys** [matthias-k/pysaliency#4]
the list of required packages is still missing ;-)

**Comment by leongatys** [comment]
required packages to import pysaliency:
boltons
dill
natsort
tqdm
https://github.com/matthias-k/optpy.git

**Comment by harrisonford** [comment]
You could include the requirements.txt file in the GIT using pip command in console while in the virtual environment you use:

`pip freeze > requirements.txt`

**Comment by matthias-k** [comment]
I finally added a requirements file (although now also setup.py should include the needed dependencies).
