### ISSUE TITLE
Can't use pysaliency in salicon 

### ISSUE THREAD

**Issue by ysyscool** [matthias-k/pysaliency#6]
Hello, I find that the url to download salicon dataset is changed. So I can't use your code in salicon.

**Comment by matthias-k** [comment]
Hi,

thanks for the report. I will add the new URLs asap. Also, there will be the 2017 version of the SALICON dataset, which uses a different way to extract fixations from the mouse movements than the original dataset.

**Comment by matthias-k** [comment]
This turns out to be more involved than I thought, since not only the links have changed, the data is now saved in a completely different way. I'll see what I can do with this data. Plus, it's on google drive now, where it is not as easy to download the file automatically.

**Comment by matthias-k** [comment]
@ysyscool It took some time but I finally had time to fix this. SALICON works again plus now there are all four versions of it (2015 and 2017, each with mouse traces or inferred fixations).
