### ISSUE TITLE
Having issues with pysaliency.external_datasets.coco_freeview.get_COCO_Freeview_train

### ISSUE THREAD

**Issue by nisar2** [matthias-k/pysaliency#74]
Hi,

This is a great repo! I had an issue with the pysaliency.external_datasets.coco_freeview.get_COCO_Freeview_train function. Specifically, it seems that the function creates the stimuli and fixations, but then crashes out at the very end with the following error:

``` bash
UFuncTypeError: ufunc 'logical_or' did not contain a loop with signature matching types (None, <class 'numpy.dtypes.StrDType'>) -> None
```
Would someone be able to help me resolve this error? 

BTW, I was able to work with the MIT1003 and CAT2000 datasets using this repo. 

All the best!

**Comment by matthias-k** [comment]
Hi! Thanks for the report! I guess this is related to a bug that I'm just fixing in the COCO Search18 dataset, which uses very similar code. It seems to be a regression as a result of my recent refactoring. If the bugfix for COCO Search18 doesn't happen to also fix this bug, I'll check it out in more detail.

**Comment by nisar2** [comment]
Awesome, thanks for the update. Any idea when the bug may be fixed?

**Comment by matthias-k** [comment]
@nisar2 now :).
